### ISSUE TITLE
pandas error in transform_nbest 

### ISSUE THREAD

**Issue by raulpuric** [dmis-lab/biobert#104]
Hi, I'm trying to evaluate my qa model on bioasq. However, given a properly formatted nbest file I'm running into the following error with pandas.

```
bash-4.4# python ./biocodes/transform_nbset2bioasqform.py --nbest_path=./preds-4b-1.json.nbest --output_path=./preds-4b-1.json.nbest.transformed
Traceback (most recent call last):
  File "./biocodes/transform_nbset2bioasqform.py", line 54, in <module>
    text = sortedDf.ix[index]["text"]
  File "/opt/conda/lib/python3.6/site-packages/pandas/core/generic.py", line 5274, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'ix'
```

Any idea as to what may be causing this? Thanks for your help!

**Comment by wonjininfo** [comment]
Hi, 
That is because of the pandas version. Pandas 1.0 is released [(January 29, 2020)](https://pandas.pydata.org/pandas-docs/version/1.0.0/whatsnew/v1.0.0.html#removal-of-prior-version-deprecations-changes) and they removed `.ix`.
```
pandas==0.23
```
Please use 0.23 version of pandas or check [here](https://stackoverflow.com/questions/59991397/attributeerror-dataframe-object-has-no-attribute-ix)

**Comment by raulpuric** [comment]
That worked like a charm. Thanks a bunch. The iloc solution was relatively easy to implement.
