### ISSUE TITLE
I can't download the dataset?

### ISSUE THREAD

**Issue by zwd13122889** [dmis-lab/biobert#121]
can you share me
![image](https://user-images.githubusercontent.com/49578851/83343205-c3ab6e00-a329-11ea-99dd-609970863aee.png)   such dataset?

**Comment by wonjininfo** [comment]
Hi, 
I just check the links and the links work for me. 
I received a few emails that the link is not working from some locations, majorly computers from companies. 
It looks like some institutes disabled downloading function from google cloud if the file is not from their organization.
Please try downloading from another location or drop us an email, so that we can share the dataset with you. 
Thank you
Wonjin
