### ISSUE TITLE
How much GPU memory needed for the Bert-large model?

### ISSUE THREAD

**Issue by brickee** [dmis-lab/biobert#124]
I try to fine-tune the Bert-large model but fail because of exhausted GPU memory. I use 4 1080 Ti GPU with a total of 44g memory but cannot run the model even with batch size as 1!

**Comment by wonjininfo** [comment]
Hi, 
You can make a GPU cluster with 4 GPUs. But as long as I know, a GPU cluster does not work like a single GPU with big memory. 
Unfortunately, BERT-LARGE requires more than 16GB (single GPU) for training steps, even if you reduced mini-batch size to 1 (since there is some constant memory uses for vocab, training with 1 batch size does not mean it needs 12 times smaller memory then training with batch size of 12). 
This explains the reason why you failed to train BioBERT-LARGE. 

We failed to train the BioBERT-LARGE model on TITAN Xp (which has 12GB) for QA task. 

Hence you will need GPUs like TITAN RTX (24GB), V100 (16GB) or K80 (24GB). 
We recommend GPU with 24GB graphic memory.

**Comment by brickee** [comment]
Thanks very much!

**Comment by yangxia605** [comment]
hi,I am not familiar with the tf code,can you tell me how to modify the code to run on GPU?
thanks!!!
