### ISSUE TITLE
BioASQ datasets issues

### ISSUE THREAD

**Issue by LauSama** [dmis-lab/biobert#29]
I find that the data used in test data are SQuAD form , and the context used are not the same as the snippets in task B-Phase B test files, I also read your paper, and confused of the data preprocessing, so i wonder where and how you get the source of the contexts?

**Comment by wonjininfo** [comment]
Hi,
The "contexts" fields are retrieved from PubMed using URLs of "documents" section. 
Since we compared our scores with BioASQ leaderboard, we followed guidelines of the challenge. 
Please see http://participants-area.bioasq.org/general_information/Task7b/ for detailed rules of BioASQ challenge.

However, we recently found that utilizing snippets doesn't show a significant difference in performance when handled with proper pre/post-processing methods. (Sometimes experiments with snippets shows better results.)

We are planning to release additional codes and data along with an updated version of pre-trained model within a few weeks. 

Thank you for your interest in our paper and have a nice weekend :)
Best,
WonJin
