### ISSUE TITLE
BioASQ-test issues

### ISSUE THREAD

**Issue by LauSama** [dmis-lab/biobert#31]
as the links: 
[https://github.com/dmis-lab/biobert#question-answering-qa](url)
**pre-processed version of BioASQ-4/5b datasets,** the answer in BioASQ doesn't offer any **answer start** information, how can you get this information like **answer start** and the **answer** in the test file?

**Comment by wonjininfo** [comment]
Comments in naver/biobert-pretrained#3 would be an answer for your question.
Also, we would like to recommend you to use the latest QA dataset (along with improved biocodes/transform_nbset2bioasqform.py code) which we released today.
Thank you for your interests on our work.
With best, 
Wonjin

**Comment by felixgaschi** [comment]
Hi !
I'd like to reopen this issue since in the new version of the preprocessed dataset, information about the answer are not available in the test file. They can yet be found in the golden files, but matching pairs of (documents/question) in the test file and its corresponding golden file is not straightforward because of several problems:
- there are more pairs in the golden file than in the corresponding test file (even when you remove all the non factoids)
- sometimes the indices of the answer for a given snippet in the golden file do not match the expected answer in the corresponding context in the test file

Maybe I've missed something, but it seems it would be simpler if information about the answer were available in the test file. I want to compute a f1-score as it is usually done for SQuAD. 

Would it be possible to have the answers in the test file or do you have a git repo with your preprocessing code of BioASQ ?
