### ISSUE TITLE
can't find `BioASQ-train-4b.json` for run_qa.py example

### ISSUE THREAD

**Issue by ahmednasserswe** [dmis-lab/biobert#52]
while running 
```
python run_qa.py \
     --do_train=True \
     --do_predict=True \
     --vocab_file=$BIOBERT_DIR/vocab.txt \
     --bert_config_file=$BIOBERT_DIR/bert_config.json \
     --init_checkpoint=$BIOBERT_DIR/biobert_model.ckpt \
     --max_seq_length=384 \
     --train_batch_size=12 \
     --learning_rate=5e-6 \
     --doc_stride=128 \
     --num_train_epochs=5.0 \
     --do_lower_case=False \
     --train_file=$BIOASQ_DIR/BioASQ-train-4b.json \
     --predict_file=$BIOASQ_DIR/BioASQ-test-4b-1.json \
     --output_dir=/tmp/QA_output/
```

I can't find `BioASQ-train-4b.json` in the referred files. 
I can find `BioASQ-train-factoid-4b.json`

but when I use it with batch size = 12 , I get the following error:
```
ValueError: train batch size 12 must be divisible by number of replicas 8
```

**Comment by wonjininfo** [comment]
Hi @ahmednasserswe , 

Apologies for the delay in getting back to you.

Recently, we updated `BioASQ-train-4b.json` while we prepare for the journal release. 
Please be kindly understand that it was my mistake to write the name of the file as `BioASQ-train-factoid-4b.json`. 

It looks like your problem is associated with TPU hardware spec.
Please check [this comment](https://github.com/google-research/bert/issues/67) from google BERT repo.

Thanks!!
Wonjin
