### ISSUE TITLE
Too much Prediction Time

### ISSUE THREAD

**Issue by hegebharat** [dmis-lab/biobert#63]
After training the Bert classification model it is taking 4 sec to predict.
I have following questions

1) is it because of loading time? If yes, can we load one time and use it for multiple inference.
2) Or is it because of computation time? If yes, what are possible way to reduce it?
3) Any advice to reduce the inference time?
5) By how much factor we can speed up the inference in CPU?

Thanks All

**Comment by jhyuklee** [comment]
Hi, I think the problem here is not only for BioBERT, but also for BERT, too (as you issued in [here](https://github.com/google-research/bert/issues/933) as well). My suggestion is to benchmark the speed for each component (model/data/etc), and optimize the code by yourself. For example, you can see [this BioNER tool](https://github.com/dmis-lab/bern) based on BioBERT which has been optimized for faster inference (which is still quite slow). If you have any progress, please tell us. Thanks!
