### ISSUE TITLE
How is Development set used during prediction time?

### ISSUE THREAD

**Issue by ghost** [dmis-lab/biobert#72]
I am trying to obtain predictions on my (unannotated) text data (tokenized and converted to .tsv file). However, it requires a devel.tsv file in the $NER_DIR even when I simply want to obtain predictions. How do I obtain predictions without having a development set? Is this functionality not supported?

**Comment by AndreasSaka** [comment]
@gnakum Is it possible to share how did you create your "tokenized" text data?

**Comment by jhyuklee** [comment]
I guess you can just copy the `test.tsv` as `devel.tsv` for now. @wonjininfo Any idea?

**Comment by wonjininfo** [comment]
Hi all, 
Sorry for my belated reply. 
Yes as Jinhyuk Lee suggested, you can use `test.tsv` as `devel.tsv`. 
Honestly, there are some rough parts in our code (especially for NER code), since our code is developed to show the utility of BioBERT pre-trained weights.
Sorry for causing confusion and thank you for your interest!
